#!/usr/bin/env bash
# prefetch-cache.sh — download/build every artifact a template build
# needs BEFORE the build starts, into the single cache tree
# ~/.cache/labloop/ (plan: docs/e-plans/plan-20260930-1838Z--offline-
# build-prefetch.md). The guest then consumes the cache over a
# transient http server on the NAT gateway instead of hitting the
# internet mid-install.
#
#   ./selfbuild/prefetch-cache.sh             # --ensure (default)
#   ./selfbuild/prefetch-cache.sh --verify    # report only; rc=1 on gaps
#   ./selfbuild/prefetch-cache.sh --refresh   # re-fetch everything
#   ./selfbuild/prefetch-cache.sh --only apt  # warm just one layer
#
# Env:  LABLOOP_OFFLINE=1        never fetch; missing artifact => fail
#       LABLOOP_CACHE_MAX_AGE_HOURS   (default 24 — ISO exempt: it is
#                                     sha256-verified at use time)
#       LABLOOP_CACHE_MIN_FREE_GIB    (default 8 — image tarballs are GBs)
#       ML_SCIENTIST             path to ml-scientist (default ../ml-scientist)
#       XDG_CACHE_HOME           cache root override
#
# GUEST_PKGS is the single source of truth for the guest package set —
# the apt-get lines in create-lab-template must match this list.
set -euo pipefail
cd "$(dirname "$0")/.."
REPO="$PWD"

CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/labloop"
ML_SCIENTIST="${ML_SCIENTIST:-$REPO/../ml-scientist}"
MAX_AGE_MIN=$(( ${LABLOOP_CACHE_MAX_AGE_HOURS:-24} * 60 ))
MIN_FREE_GIB="${LABLOOP_CACHE_MIN_FREE_GIB:-8}"
OFFLINE="${LABLOOP_OFFLINE:-0}"

# every apt package the guest installs (in-target + provisioning);
# codium's own dep closure is appended at fetch time via --print-uris
# on the local .deb — do not duplicate create-lab-template's lists here
GUEST_PKGS=(
    qemu-guest-agent spice-vdagent
    podman uidmap acl pipx python-is-python3 git curl mc nodejs npm nftables
    texlive-latex-base texlive-latex-recommended texlive-fonts-recommended latexmk
    numlockx
)
TRIAL_PKGS="numpy pandas scipy scikit-learn matplotlib reportlab"
UVX_PKGS="uv duckduckgo-mcp-server"
VSIX_EXTS="ZooCodeOrganization.zoo-code tomoki1207.pdf"

# opencode version: create-lab-template's npm line is the single source
# of truth — read it up front so have_pkgs can demand THIS version (a
# bump there must make the pkgs layer non-ok, else ensure never refetches)
OC_VER=$(grep -oE '@opencode/cli@[0-9]+\.[0-9]+\.[0-9]+' \
         "$REPO/create-lab-template" | head -1 | cut -d@ -f3)

die()  { echo "prefetch-cache: $*" >&2; exit 1; }
note() { echo "==> $*"; }
say()  { echo "    $*"; }

MODE=ensure; ONLY=""
case "${1:-}" in
    --ensure|"") ;;
    --verify)  MODE=verify ;;
    --refresh) MODE=refresh ;;
    --only)    ONLY="${2:?--only needs a layer name}" ;;
    -h|--help) sed -n '2,25p' "$0"; exit 0 ;;
    *) die "unknown flag '$1'" ;;
esac

mkdir -p "$CACHE"/{apt,images,wheels/trial-env,wheels/uvx,pkgs}

# ISO identity lives in mk-auto-iso.sh — eval its four assignments so a
# Mint point-release bump can't drift the two scripts apart
eval "$(sed -n '/^ISO_NAME=/p;/^ISO_URL=/p;/^SUMS_URL=/p;/^ISO_CACHE=/p' \
        "$REPO/selfbuild/mk-auto-iso.sh")"
mkdir -p "$ISO_CACHE"

# ------------------------------------------------------------------
# per-layer presence checks
# ------------------------------------------------------------------
have_iso()    { compgen -G "$ISO_CACHE/linuxmint-*-xfce-64bit.iso" >/dev/null; }
have_apt()    { [ -f "$CACHE/apt/Packages.gz" ] \
                && compgen -G "$CACHE/apt/*.deb" >/dev/null; }
have_images() { compgen -G "$CACHE/images/lab-img-mcp-*.tar" >/dev/null \
                && compgen -G "$CACHE/images/lab-img-exp-*.tar" >/dev/null; }
have_wheels() { compgen -G "$CACHE/wheels/trial-env/*.whl" >/dev/null \
                && compgen -G "$CACHE/wheels/uvx/uv-*.whl" >/dev/null \
                && compgen -G "$CACHE/wheels/uvx/duckduckgo*" >/dev/null; }
have_pkgs()   { compgen -G "$CACHE/pkgs/codium_*.deb" >/dev/null \
                && [ -f "$CACHE/pkgs/opencode-cli-linux-x64-${OC_VER}.tgz" ] \
                && [ -f "$CACHE/pkgs/opencode-cli-linux-x64-baseline-${OC_VER}.tgz" ] \
                && [ "$(find "$CACHE/pkgs" -name '*.vsix' | wc -l)" -ge 2 ]; }

# stale = a layer with ANY file older than the age cap (fetchers
# re-fetch the whole layer — a stale artifact is never silently kept)
fresh() { [ -z "$(find "$1" -type f -mmin +"$MAX_AGE_MIN" -print -quit 2>/dev/null)" ]; }
iso_fresh() { return 0; }   # exempt — sha256-verified at use time

LAYERS=(iso apt images wheels pkgs)
declare -A LAYER_DIR=(
    [iso]="$ISO_CACHE" [apt]="$CACHE/apt" [images]="$CACHE/images"
    [wheels]="$CACHE/wheels" [pkgs]="$CACHE/pkgs")

manifest_regen() {
    ( cd "$CACHE"
      printf '# labloop artifact manifest — regenerated by prefetch-cache.sh; do not edit\n'
      find . -type f ! -name 'MANIFEST*' -printf '%P\n' | sort | while read -r p; do
          printf '%s\t%s\t%s\t%s\n' "$p" "$(stat -c%s "$p")" \
              "$(sha256sum "$p" | cut -d' ' -f1)" \
              "$(date -u -r "$p" +%FT%TZ)"
      done ) > "$CACHE/MANIFEST.tmp"
    mv "$CACHE/MANIFEST.tmp" "$CACHE/MANIFEST"
}

# verify_manifest — every file on disk must hash to its manifest row.
# A file absent from MANIFEST is untracked, not corrupt (first-run case).
verify_manifest() {
    [ -f "$CACHE/MANIFEST" ] || return 0
    local bad=0 p sha
    while IFS=$'\t' read -r p _ sha _; do
        case "$p" in '#'*|'') continue ;; esac
        [ -f "$CACHE/$p" ] || continue
        [ "$(sha256sum "$CACHE/$p" | cut -d' ' -f1)" = "$sha" ] \
            || { say "BAD HASH: $p"; bad=1; }
    done < "$CACHE/MANIFEST"
    return $bad
}

# ------------------------------------------------------------------
# fetchers — each repopulates one layer; all run host-side, online
# ------------------------------------------------------------------
fetch_iso() {
    command -v curl >/dev/null || die "curl required"
    if have_iso; then say "iso: cached"; return; fi
    note "iso: downloading $ISO_NAME"
    curl -fsSL -o "$ISO_CACHE/sha256sum.txt" "$SUMS_URL" \
        || die "cannot fetch Mint checksums ($SUMS_URL)"
    curl -fL --progress-bar -o "$ISO_CACHE/$ISO_NAME.part" "$ISO_URL"
    mv "$ISO_CACHE/$ISO_NAME.part" "$ISO_CACHE/$ISO_NAME"
    ( cd "$ISO_CACHE" && grep -F "$ISO_NAME" sha256sum.txt | sha256sum -c - ) \
        || { rm -f "$ISO_CACHE/$ISO_NAME"; die "ISO checksum FAILED"; }
}

fetch_apt() {
    command -v curl dpkg-scanpackages >/dev/null \
        || die "curl + dpkg-scanpackages (dpkg-dev) required"
    note "apt: resolving guest package closure (empty-status print-uris)"
    local scratch; scratch="$(mktemp -d)"
    mkdir -p "$scratch/lists/partial" "$scratch/cache/archives/partial"
    # per-user lists dir: the resolve needs fresh indexes without sudo
    apt-get update -qq \
        -o Dir::State::Lists="$scratch/lists" \
        -o Dir::Cache="$scratch/cache"
    # pseudo-status = exactly what the installed guest already has.
    # Best source: filesystem.manifest inside the cached ISO (the real
    # squashfs baseline — verified: ~490-deb closure vs ~900 without it).
    # Fallback: mark only Essential/required/important as installed.
    # A fully empty status would drag the base system into the bundle;
    # the host's real status would silently drop packages the host
    # already has (podman etc.) out of the guest's closure.
    local fsm="$scratch/fsm"; mkdir -p "$fsm"
    if xorriso -osirrox on -indev "$ISO_CACHE/$ISO_NAME" \
        -extract /casper/filesystem.manifest "$fsm/filesystem.manifest" \
        >/dev/null 2>&1 && [ -s "$fsm/filesystem.manifest" ]; then
        awk -F'\t' '{p=$1; a="amd64";
            if (p ~ /:/) {split(p,b,":"); p=b[1]; a=b[2]}
            printf "Package: %s\nStatus: install ok installed\nVersion: %s\nArchitecture: %s\n\n",p,$2,a}' \
            "$fsm/filesystem.manifest" > "$scratch/status"
        say "apt: pseudo-status from ISO filesystem.manifest ($(grep -c '^Package:' "$scratch/status") pkgs)"
    else
        say "apt: no ISO manifest — falling back to essential-only status"
        cat "$scratch"/lists/*_Packages | awk '
            /^Package: /{p=$2} /^Version: /{v=$2} /^Essential: /{e=$2}
            /^Priority: /{pr=$2} /^Architecture: /{a=$2} /^Multi-Arch: /{m=$2}
            /^$/ { if(e=="yes"||pr=="required"||pr=="important") {
                printf "Package: %s\nStatus: install ok installed\nVersion: %s\nArchitecture: %s\n",p,v,a;
                if(m!="") printf "Multi-Arch: %s\n",m; printf "\n" }
              e="";pr="";a="";m="" }' > "$scratch/status"
    fi
    local cod_deb=""
    cod_deb="$(compgen -G "$CACHE/pkgs/codium_*.deb" || true)"
    {
        apt-get install --print-uris -y \
            -o Dir::State::Lists="$scratch/lists" \
            -o Dir::Cache="$scratch/cache" \
            -o Dir::State::Status="$scratch/status" \
            "${GUEST_PKGS[@]}"
        [ -z "$cod_deb" ] || apt-get install --print-uris -y \
            -o Dir::State::Lists="$scratch/lists" \
            -o Dir::Cache="$scratch/cache" \
            -o Dir::State::Status="$scratch/status" \
            "$CACHE/pkgs/$(basename "$cod_deb")"
    } | grep -oE "'[^']+' [^ ]+_(amd64|all)\.deb" \
      | tr -d "'" > "$scratch/uris"
    local n; n=$(wc -l < "$scratch/uris")
    note "apt: fetching $n debs"
    local fail=0 url fn
    while read -r url fn; do
        [ -f "$CACHE/apt/$fn" ] && continue
        curl -fsSL -o "$CACHE/apt/$fn" "$url" \
            || { say "MISS: $fn"; fail=1; }
    done < "$scratch/uris"
    rm -rf "$scratch"
    [ "$fail" = 0 ] || die "apt layer incomplete — $n debs resolved, some fetches failed"
    ( cd "$CACHE/apt" && dpkg-scanpackages . /dev/null 2>/dev/null | gzip -9 > Packages.gz )
    have_apt || die "apt bundle produced no debs"
}

fetch_images() {
    command -v podman >/dev/null || die "podman required (host-side image bake)"
    [ -f "$ML_SCIENTIST/pyproject.toml" ] && [ -d "$ML_SCIENTIST/src" ] \
        || die "ML_SCIENTIST=$ML_SCIENTIST missing pyproject.toml/src"
    # free space first — the two tarballs run ~1-3 GB
    local avail; avail=$(df -BG --output=avail "$CACHE" | tail -1 | tr -dc 0-9)
    [ "$avail" -ge "$MIN_FREE_GIB" ] \
        || die "only ${avail}GiB free under $CACHE (need $MIN_FREE_GIB)"
    note "images: staging ml-scientist ctx (same sanitize as create-lab-template)"
    local ctx; ctx="$(mktemp -d)"
    mkdir -p "$ctx/mcp/ml-scientist"
    tar -C "$ML_SCIENTIST" --exclude='./.git' --exclude='./docs' -cf - . \
        | tar -xf - -C "$ctx/mcp/ml-scientist"
    find "$ctx/mcp/ml-scientist" -name '*.md' -delete
    printf '# ml-scientist\n\nMCP runtime sources (documentation stripped).\n' \
        > "$ctx/mcp/ml-scientist/README.md"
    local rev dirty
    rev=$(git -C "$ML_SCIENTIST" rev-parse --short HEAD 2>/dev/null || echo nogit)
    if [ -n "$(git -C "$ML_SCIENTIST" status --porcelain 2>/dev/null | head -1)" ]; then
        dirty=true; rev="$rev-dirty"
    else
        dirty=false
    fi
    printf '{"rev": "%s", "dirty": %s}\n' "${rev%-dirty}" "$dirty" \
        > "$ctx/mcp/ml-scientist/BUILD_REV"
    cp "$REPO/containers/mcp/Containerfile" \
       "$REPO/containers/mcp/entrypoint.sh" "$ctx/mcp/"
    note "images: podman build lab-img-mcp + lab-img-exp (host-side, online)"
    podman build -t lab-img-mcp -f "$ctx/mcp/Containerfile" "$ctx/mcp"
    podman build -t lab-img-exp "$REPO/containers/experiment"
    note "images: saving -> $CACHE/images (docker-archive, rev $rev)"
    podman save --format docker-archive \
        -o "$CACHE/images/lab-img-mcp-$rev.tar" lab-img-mcp
    podman save --format docker-archive \
        -o "$CACHE/images/lab-img-exp-$rev.tar" lab-img-exp
    # drop tarballs of superseded revs — each pair is multi-GB
    find "$CACHE/images" -name 'lab-img-*.tar' ! -name "*-$rev.tar" -delete
    rm -rf "$ctx"
}

fetch_wheels() {
    # download inside the target interpreter so wheel tags match the
    # guest's py3.12 (host python may differ)
    command -v podman >/dev/null || die "podman required (wheel downloads run in python:3.12-slim)"
    note "wheels: trial-env + uvx closures (inside python:3.12-slim)"
    podman run --rm -v "$CACHE/wheels:/out:z" docker.io/library/python:3.12-slim \
        pip download --no-cache-dir -d /out/trial-env $TRIAL_PKGS
    podman run --rm -v "$CACHE/wheels:/out:z" docker.io/library/python:3.12-slim \
        pip download --no-cache-dir -d /out/uvx $UVX_PKGS
    have_wheels || die "wheel layer incomplete"
}

fetch_pkgs() {
    command -v curl npm >/dev/null || die "curl + npm required"
    note "pkgs: opencode tarball, codium deb, vsix extensions"
    # the launcher package is a 2 KB postinstall shim whose real
    # payload is a per-platform optionalDependency (still a registry
    # fetch even from the tgz) — so we pack the linux-x64 tarballs
    # directly and the guest installs package/bin/opencode straight to
    # /usr/local/bin, choosing baseline vs regular by /proc/cpuinfo
    # exactly like the package's postinstall.mjs. OC_VER comes from
    # create-lab-template's npm pin (single source of truth).
    [ -n "$OC_VER" ] || die "cannot read opencode pin from create-lab-template"
    ( cd "$CACHE/pkgs" && npm pack "@opencode/cli@$OC_VER" --silent >/dev/null \
        && npm pack "@opencode/cli-linux-x64@$OC_VER" --silent >/dev/null \
        && npm pack "@opencode/cli-linux-x64-baseline@$OC_VER" --silent >/dev/null )
    # superseded-version tarballs are dead weight (~88 MB each) and
    # would let a stale glob match satisfy the pin — drop them
    find "$CACHE/pkgs" -name 'opencode-cli*.tgz' \
        ! -name "*-${OC_VER}.tgz" -delete
    # codium: latest GitHub release amd64 .deb (replaces the gitlab apt repo)
    local rel url
    rel=$(curl -fsSL https://api.github.com/repos/VSCodium/vscodium/releases/latest)
    url=$(printf '%s' "$rel" | grep -oE '"browser_download_url": *"[^"]*_amd64\.deb"' \
          | grep -oE 'https:[^"]*' | head -1)
    [ -n "$url" ] || die "no amd64 .deb in latest VSCodium release"
    curl -fL --progress-bar -o "$CACHE/pkgs/$(basename "$url")" "$url"
    # vsix: open-vsx download endpoint per extension
    local ext ns name j u
    for ext in $VSIX_EXTS; do
        ns="${ext%%.*}"; name="${ext#*.}"
        j=$(curl -fsSL "https://open-vsx.org/api/$ns/$name") \
            || die "open-vsx: $ext metadata fetch failed"
        u=$(printf '%s' "$j" | grep -oE '"download"[^,}]*' \
            | grep -oE 'https:[^"]*' | head -1)
        [ -n "$u" ] || die "open-vsx: no download URL for $ext"
        curl -fsSL -o "$CACHE/pkgs/$(basename "$u")" "$u"
    done
    have_pkgs || die "pkgs layer incomplete"
}

# ------------------------------------------------------------------
# status + driver
# ------------------------------------------------------------------
status_line() {  # layer -> "ok" | "stale" | "missing"
    local l=$1
    "have_$l" || { echo missing; return; }
    # iso is hash-verified at use; staleness does not apply
    if [ "$l" != iso ] && ! fresh "${LAYER_DIR[$l]}"; then echo stale; return; fi
    echo ok
}

report() {
    echo "    artifact cache: $CACHE"
    for l in "${LAYERS[@]}"; do
        printf '    %-8s %s\n' "$l" "$(status_line "$l")"
    done
    verify_manifest && echo "    manifest: all hashes ok"
}

note "preflight: labloop artifact cache ($MODE$([ "$OFFLINE" = 1 ] && echo ', OFFLINE'))"
report

needs_fetch=()
if [ -n "$ONLY" ]; then
    case " ${LAYERS[*]} " in *" $ONLY "*) ;; *) die "no such layer '$ONLY'" ;; esac
    needs_fetch=("$ONLY")
else
    for l in "${LAYERS[@]}"; do
        s=$(status_line "$l")
        if [ "$MODE" = refresh ] || [ "$s" != ok ]; then
            [ "$s" = stale ] && say "$l: stale (>${LABLOOP_CACHE_MAX_AGE_HOURS:-24}h) — refreshing"
            needs_fetch+=("$l")
        fi
    done
fi

if ((${#needs_fetch[@]})); then
    # hard gaps = missing/corrupt; stale is soft (usable when offline)
    hard=()
    for l in "${needs_fetch[@]}"; do
        [ "$(status_line "$l")" = stale ] || hard+=("$l")
    done
    if [ "$OFFLINE" = 1 ]; then
        ((${#hard[@]})) && {
            printf '    GAPS: %s\n' "${hard[*]}" >&2
            die "offline build but cache incomplete — cannot proceed"
        }
        say "WARN: stale layers kept (offline, nothing better to fetch): ${needs_fetch[*]}"
        needs_fetch=()
    elif [ "$MODE" = verify ]; then
        printf '    GAPS: %s\n' "${needs_fetch[*]}" >&2
        die "cache incomplete — warm it with ./selfbuild/prefetch-cache.sh"
    fi
fi

if ((${#needs_fetch[@]})); then
    # pkgs first: the apt closure step reads pkgs/codium_*.deb for
    # codium's own dependency list
    ordered=()
    for l in pkgs iso apt images wheels; do
        case " ${needs_fetch[*]} " in *" $l "*) ordered+=("$l");; esac
    done
    for l in "${ordered[@]}"; do "fetch_$l"; done
    manifest_regen
    note "re-verify after prefetch"
    report
fi

for l in ${ONLY:-${LAYERS[*]}}; do
    s=$(status_line "$l")
    case "$s" in
        ok) ;;
        stale) say "WARN: $l stale but kept (offline — nothing better exists)" ;;
        *) die "layer '$l' still incomplete after prefetch" ;;
    esac
done
verify_manifest || die "manifest hash mismatch"

if [ -n "$ONLY" ]; then
    echo "    preflight: layer '$ONLY' ok"
else
    echo "    preflight: ${#LAYERS[@]}/${#LAYERS[@]} layers ok"
fi
